# Generated by Django 4.2.17 on 2024-12-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
